### ISSUE TITLE
Error when generating about page

### ISSUE THREAD

**Issue by MichaelKim39** [JamesDHW/next-notion-blog-builder#1]
Getting this error when I try to run `npx next-notion-blog-builder` with the `about` page selected for generation

`Oops, something went wrong:
Error: ENOENT: no such file or directory, lstat '/Users/michaelkim/node_modules/next-notion-blog-builder/dist/templates/extra-pages/about/components'`

Looking through the folder in `node_module`, there is no `components` folder in my `about` folder so this is probably the cause of the issue

**Comment by JamesDHW** [comment]
Hey Michael, thanks for this issue!

I created this directory locally when working on this called `/extra-pages/about/component`, so this worked fine in development, however `git` and `npm publish` only track files (not directories), so an empty local directory doesn't get tracked in `git` history or when pushing with `npm publish`. Not syncing empty directories is good practice - a program shouldn't depend on having a specific directory structure ☺️ 

This meant that you don't get the same directory structure as me when running `npx next-notion-blog-builder` which means `copySync` from [fs-extra](https://www.npmjs.com/package/fs-extra) throws an error.

The fix is to add in [ensureDirSync](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/ensureDir-sync.md) before trying [copySync](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/copy-sync.md). Here's the [commit](https://github.com/JamesDHW/next-notion-blog-builder/commit/be5e3c458aace4de82e0a9e9aded29086af15911).
