### ISSUE TITLE
static import casing causes build failures on Vercel

### ISSUE THREAD

**Issue by MichaelKim39** [JamesDHW/next-notion-blog-builder#2]
Here is an example of a Vercel build failure

<img width="927" alt="image" src="https://user-images.githubusercontent.com/32578159/219129061-fa890324-fe2d-4dbf-9165-488f91fe4308.png">

Vercel complains that the module cannot be found, because the static imports in code sometimes reference `Common` with a capital c rather than `common` with a lowercase c. This is being caught as expected by the typescript rule `"forceConsistentCasingInFileNames": true,` but has not been addressed in code. The fix is to change all instances of `Common` with `common`. 

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/32578159/219129478-0e4bac4e-7be9-4d85-a14a-31d7f7cdaf89.png">

**Comment by JamesDHW** [comment]
Hey Michael, once again, thanks for submitting the issue - I just discovered this myself yesterday evening but didn't have a chance to fix it immediately (I should have submitted the issue myself for the visibility of others!). It was a quick fix - see the [commit](https://github.com/JamesDHW/next-notion-blog-builder/commit/fc30e12777a14a9156c3184a7e7f7b7d4a14acff). The fix is now pushed to [npmjs](https://www.npmjs.com/package/next-notion-blog-builder) as of 1.0.9!

On another note, glad to see you got your blog up and running!
